### ISSUE TITLE
babel-cli and babel-preset-env should be dev-dependencies

### ISSUE THREAD

**Issue by wooorm** [derhuerst/hast-to-snabbdom#2]
https://github.com/syntax-tree/hast-util-to-snabbdom/blob/0e3c53a9153654f8e8ce1881294ca11aaf54850b/package.json#L26-L27

Right?

**Comment by derhuerst** [comment]
Yes, indeed.

**Comment by wooorm** [comment]
Pushed a fix, but I can’t publish it!
Could you either add me on npm, or publish yourself?

**Comment by derhuerst** [comment]
I added you.
